# Generated by Django 2.2.1 on 2019-05-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('namespace', models.CharField(max_length=50)),
                ('firstCommitDate', models.DateTimeField()),
                ('contibutors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick_okra.Contributor')),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick_okra.RepositoryMetrics')),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick_okra.Repository'),
        ),
    ]
